services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - .:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    ports:
      - "8080:8080"
    volumes:
      - .:/app/backend/data
      - ./doc:/data/docs
    extra_hosts:
      - "host.docker.internal:host-gateway"
